language: node_js
node_js: '9'
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
before_script: npm install -g polymer-cli
script: xvfb-run polymer test
